#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. &&pwd )"
CONFIG_DIR="${SCRIPT_DIR}/include"
FOUNDATION="$1"

if [ ! -d ${CONFIG_DIR} ]
then
	echo "Setting up the config directory for the first time..."
	mkdir -p ${CONFIG_DIR}
	echo
fi

FILE="${CONFIG_DIR}/api_endpoints"

if [ ! -f ${CONFIG_DIR}/api_endpoints ]
then
	echo "Setting up the config for cf login...."
	echo
        echo "Enter foundation alias: "
        read -e foundation
        echo "Enter api endpoint url: "
        read -e api
        echo "# Foundation      API_Endpoint" >> ${FILE}
        echo "$foundation       $api" >> ${FILE}
	echo "Done" 
	echo
	echo
fi

# Check if already logged in
cf target > /dev/null 2>&1
if [ $? -eq 0 ]
then
	if [ `cf target | grep endpoint | awk -F. '{print $3}'` == "${FOUNDATION}" ]
	then
		cf target -o sys-tmo -s production > /dev/null 2>&1
		if [ $? -eq 0 ]
		then
			echo "CF login to ${FOUNDATION} is good."
			exit
		fi
	fi
fi

if [[ `cat ${FILE} | grep -w ${FOUNDATION} | wc -l` -eq 0 ]]
then
	echo "not a valid foundation name. Update ${FILE} file to include this new foundation!"
        echo "api-endpoint config has not been setup yet. Want to try setting up the configs. "
        echo "Continue (y|n): "
        while read -e answer
        do
          if [ ${answer^^} == "Y" ]
          then
                foundation=${FOUNDATION}
                echo "Enter api endpoint url: "
                read -e api
                echo "$foundation 	$api" >> ${FILE}
		break
          elif [ ${answer^^} == "N" ]
          then
                echo "Exiting...."
                exit
          else
                printf "Not a valid answer. Continue (y|n): "
          fi
        done
        echo "Completed setting up the config. "
        echo
        echo
fi
echo "Enter user ID:"
read -e ID

ENDPT=`cat ${FILE} | grep -w ${FOUNDATION} | awk '{print $NF}'`
cf login -a ${ENDPT} -u ${ID} -o system -s system 2>/dev/null
